### ISSUE TITLE
It won't run with the default settings

### ISSUE THREAD

**Issue by caoshuai888** [Debatrix/UPCL#1]
感谢您对 CIL 领域的贡献！
当我下载upcl代码后，用默认设置运行代码，出现了下面的问题，您能帮忙看看吗？
2024-06-12 21:13:55,771 [trainer.py] => 'UPCL_iCaRL' object has no attribute 'k'
Traceback (most recent call last):
  File "/home/ps/dl/shuai/UPCL-main/trainer.py", line 82, in _train
    model.incremental_train(data_manager)
  File "/home/ps/dl/shuai/UPCL-main/models/icarl.py", line 74, in incremental_train
    self._train(self.train_loader, self.test_loader)
  File "/home/ps/dl/shuai/UPCL-main/models/upcl.py", line 273, in _train
    k = min(fea_mask.sum(0).min(), self.k)
AttributeError: 'UPCL_iCaRL' object has no attribute 'k'

**Comment by Debatrix** [comment]
Thanks for the reminder, this issue was fixed in the last Commit. 
The `k` in line 273 is a hyperparameter in KCL Loss, I tried to use it to improve performance, but found that it didn't matter, so I removed the relevant code, and here is the part that was left behind.
